# Generated by Django 5.0.3 on 2024-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_offers_end_date_alter_offers_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
